### ISSUE TITLE
Add checking for undefined expressions

### ISSUE THREAD

**Issue by shareefj** [ics-jku/wal#14]
It looks like there's no checking that an expression used in a condition is valid.  For example, defining an alias on a signal but then using that signal in an expression with a typo doesn't raise an error that WAL knows nothing about the mistyped version.

So for example:

```
(alias htrans TOP.blah.blah)
(whenever clk (when (= trans 2) (print "Found it")))
```
runs with no output even though there is no expression `trans`.

**Comment by LucasKl** [comment]
This is changed in the new Version of WAL. Since WAl is heavily inspired by AWK it used to define variables on first use with 0. However, I changed this in the latest release and now an error should be thrown. 

Originally it was a nice feature for simple "one-line" scripts but as WAL programs got more complicated it produced more problems then it solved.
